set_property IOSTANDARD LVCMOS33 [get_ports TTC0_WAVE1_OUT_0]
set_property IOSTANDARD LVCMOS33 [get_ports TTC0_WAVE2_OUT_0]
set_property PACKAGE_PIN V9 [get_ports TTC0_WAVE1_OUT_0]
set_property PACKAGE_PIN W12 [get_ports TTC0_WAVE2_OUT_0]

set_property IOSTANDARD LVCMOS33 [get_ports {led_outs_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_outs_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_outs_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_outs_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_outs_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_outs_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_outs_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_outs_0[0]}]
set_property PACKAGE_PIN AB1 [get_ports {led_outs_0[0]}]
set_property PACKAGE_PIN AA4 [get_ports {led_outs_0[1]}]
set_property PACKAGE_PIN Y5 [get_ports {led_outs_0[2]}]
set_property PACKAGE_PIN AA6 [get_ports {led_outs_0[3]}]
set_property PACKAGE_PIN AB4 [get_ports {led_outs_0[4]}]
set_property PACKAGE_PIN W10 [get_ports {led_outs_0[5]}]
set_property PACKAGE_PIN W8 [get_ports {led_outs_0[6]}]
set_property PACKAGE_PIN AB11 [get_ports {led_outs_0[7]}]

