set_property IOSTANDARD LVCMOS33 [get_ports CAN_0_1_rx]
set_property IOSTANDARD LVCMOS33 [get_ports CAN_0_1_tx]
set_property IOSTANDARD LVCMOS33 [get_ports CAN_1_2_rx]
set_property IOSTANDARD LVCMOS33 [get_ports CAN_1_2_tx]
set_property PACKAGE_PIN Y14 [get_ports CAN_0_1_rx]
set_property PACKAGE_PIN AA14 [get_ports CAN_0_1_tx]
set_property PACKAGE_PIN W15 [get_ports CAN_1_2_rx]
set_property PACKAGE_PIN Y15 [get_ports CAN_1_2_tx]

# SPI LCD
set_property PACKAGE_PIN Y13 [get_ports {GPIO_0_0_tri_io[2]}]
set_property PACKAGE_PIN AA18 [get_ports {GPIO_0_0_tri_io[1]}]
set_property PACKAGE_PIN W13 [get_ports {GPIO_0_0_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_0_0_io0_io]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_0_0_sck_io]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_0_0_ss_io]
set_property PACKAGE_PIN U16 [get_ports SPI_0_0_io0_io]
set_property PACKAGE_PIN V19 [get_ports SPI_0_0_sck_io]
set_property PACKAGE_PIN AA13 [get_ports SPI_0_0_ss_io]
