domain_path: /home/kaz/work/github/seisyuu-hantatsushi/zynq/minimam_platform/SW/minimam_platform/export/minimam_platform/sw/standalone_ps7_cortexa9_0
app_src_dir: /home/kaz/tools/Xilinx/2025.2/Vitis/data/embeddedsw/lib/sw_apps/lwip_echo_server
template: lwip_echo_server
lang: c
