domain_path: /home/kaz/work/github/seisyuu-hantatsushi/zynq/simple_hello_world/SW/platform/export/platform/sw/standalone_ps7_cortexa9_0
app_src_dir: /home/kaz/tools/Xilinx/2025.2/Vitis/data/embeddedsw/lib/sw_apps/hello_world
template: hello_world
lang: c
